#!/bin/zsh

if [[ $2 == "on" ]]
then
  echo "Turning on query logging on deployment $1"
  bosh -d $1 ssh metric-store 'sudo sed -i "/env:/ a \      LOG_QUERIES: true" /var/vcap/jobs/metric-store/config/bpm.yml; sudo monit restart metric-store; sudo monit summary'
elif [[ $2 == "off" ]]
then
  echo "Turning off query logging on deployment $1"
  bosh -d $1 ssh metric-store 'sudo sed -i "/LOG_QUERIES:/ d" /var/vcap/jobs/metric-store/config/bpm.yml; sudo monit restart metric-store; sudo monit summary'
else
  echo "Usage: $0 deployment_name on|off  # toggle query logging for deployment"
fi
