version: 2
updates:
- package-ecosystem: gomod
  labels:
    - "auto-merge"
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 10
  target-branch: "develop"
