---
- name: metric_store_configs
  type: collection
  configurable: true
  optional: true
  property_blueprints:
    - name: max_concurrent_queries
      type: integer
      configurable: true
      default: 1
