#!/bin/bash -e

RUN_DIR=/var/vcap/sys/run/metric-store
LOG_DIR=/var/vcap/sys/log/metric-store
PIDFILE=${RUN_DIR}/metric-store.pid
JOB_DIR=/var/vcap/jobs/metric-store
CERT_DIR=$JOB_DIR/config/certs

PACKAGE_DIR=/var/vcap/packages/metric-store
ENVIRONMENT=/var/vcap/jobs/metric-store/bin/environment.sh

case $1 in

  start)
    set +e
      killall -15 metric-store
      killall -9 metric-store
      killall -2 metric-store
      killall -3 metric-store
    set -e

    mkdir -p $RUN_DIR $LOG_DIR
    chown -R vcap:vcap $RUN_DIR $LOG_DIR

    cd $PACKAGE_DIR

    ulimit -n 8192

    source $ENVIRONMENT

    mkdir -p $STORAGE_PATH
    chown vcap:vcap $STORAGE_PATH
    chmod 755 $STORAGE_PATH

    echo $$ > $PIDFILE
    exec chpst -u vcap:vcap ./metric-store &>> ${LOG_DIR}/metric-store.log

    ;;

  stop)
    set +e
      killall -15 metric-store
      killall -9 metric-store
      killall -2 metric-store
      killall -3 metric-store
    set -e

    rm -f $PIDFILE

    ;;

  *)
    echo "Usage: ctl {start|stop}"

    ;;

esac
