// Code generated by go-bindata. DO NOT EDIT.
// sources:
// metric-store-ca.crl (934B)
// metric-store-ca.crt (1.777kB)
// metric-store-ca.key (3.243kB)
// metric-store.crt (1.545kB)
// metric-store.csr (952B)
// metric-store.key (1.679kB)

package testing

import (
	"crypto/sha256"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

type asset struct {
	bytes  []byte
	info   os.FileInfo
	digest [sha256.Size]byte
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _metricStoreCaCrl = []byte(`-----BEGIN X509 CRL-----
MIICiTBzAgEBMA0GCSqGSIb3DQEBCwUAMBoxGDAWBgNVBAMTD21ldHJpYy1zdG9y
ZS1jYRcNMjUwNTA4MDUzMjE2WhcNMjYxMTA4MDUzMjE0WjAAoCMwITAfBgNVHSME
GDAWgBQgg2eV6YsKEFpnm6uqPotP0Z7bszANBgkqhkiG9w0BAQsFAAOCAgEAaeed
mchnSPxCI/afeEAHVE1PGNuG1QcV9vlnVMrj3Hp7HOreXqz0xm2jcALkr/T4GUSu
o2oHuzLmMZ/4XfVgGkSfumxxz6c0DrL97s7KIbQKAwEfl3AeMXZlmxBJ/Ib1MHoj
p1SG30m4pDwq1cMaG8iyBWQz2KkTV7EvR6uOXT15gKxUtOMOWPdSzgDcd+2nORbD
+qwJ53SZK0iqHab+9R4GxvPAZxxSSsp8XoXKUyihi0IlCgRUpnICx5vCqYtP5MFz
yZjGwSHxjCLgQRN4ns6UULBBfbPFR3Dn4NudG65oCy76+gawUo2YU//Bl7dYydQA
9/tu/usFOcSQe28yTFxQh/4urGm4u8Nn0JVubVYtIZNQBldm12vnF4G5YFPjTPvJ
xBb25HJ2HR2Pvo9p1u7F+9f2r8QDwJliBcix7mIIudprxTUTEo3MjBJSB3A5EeAb
1BY3Hu7BSkcztRr560B2h6bLVeov/F57f5QWuhP4CDeFWKrISDh8EIGSi44mN+bS
BWDCcrLFNORX7CslpTWuOmItPudIC5JI7X5LRYvkVbOTcb7RkPznFDHkk5sgzXPv
w8uVfp4K/RDOOepG7eI0HrCzm3UcUbAfP0j66mkCuFDT2tjvoYUoDpTCJAeeTqUE
OvR2d1ki7UNxGigkC2tQI9vm5+kNIqt3DVgW0Yo=
-----END X509 CRL-----
`)

func metricStoreCaCrlBytes() ([]byte, error) {
	return _metricStoreCaCrl, nil
}

func metricStoreCaCrl() (*asset, error) {
	bytes, err := metricStoreCaCrlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "metric-store-ca.crl", size: 934, mode: os.FileMode(0444), modTime: time.Unix(1695990541, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0xc6, 0x90, 0x24, 0x87, 0x22, 0xdf, 0x2, 0x1e, 0x3, 0x83, 0x76, 0x19, 0x27, 0xf1, 0x45, 0xdb, 0x48, 0xd3, 0xe2, 0xec, 0x92, 0xde, 0xb6, 0xca, 0x56, 0x67, 0xf2, 0x30, 0xee, 0xf0, 0xb1, 0xf8}}
	return a, nil
}

var _metricStoreCaCrt = []byte(`-----BEGIN CERTIFICATE-----
MIIE9DCCAtygAwIBAgIBATANBgkqhkiG9w0BAQsFADAaMRgwFgYDVQQDEw9tZXRy
aWMtc3RvcmUtY2EwHhcNMjUwNTA4MDUyMjE2WhcNMjYxMTA4MDUzMjE0WjAaMRgw
FgYDVQQDEw9tZXRyaWMtc3RvcmUtY2EwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAw
ggIKAoICAQDlN5Z2SKwJPWcQT5BMVoEqnRhGkZVZmRk69o9q//u3mGWHAw3c3l6O
8fhZCuzFLde2uEOLPw8H6zcRi+spzSiXiEpfKIzuYsZmMkbaZpQm/OB8kCux5DXE
iBEepcWpCQOPwapkhbkrq1vz6aUvTeBA2kAkpsLiyoyVJXbzkTl9x2NDGCEt4Dm3
RRdae1qHnX8ZzUQbxP5TOFhchHVuhp7vBeaZbC4xN4lpmYKmZtvCmbfezIjELWqS
xbOvxr6Yhwp/5Xsn9iu+ZeQzwmtfXXeiGhIScyIpXA13vpcqWyd49NRHz0vMvKhK
YCjQH9N/bLj0ZKznPTDhvcRkv1UFtNRVZ6ir/tdivL40e/2MZT/j035SWV9Ww+QR
p6DNUwDxQEGt/PstQResy1/CfyAsJhoy92H3/0v0pgFGkiiTlJLl4Fpb5bXHBisu
VQHSKpth+L89/HokVt7u9oPjBpcHQlwkWNKp/lLW1z1ZO6mnKiofEvf/xMDxjp9V
a0/3txvLKsA/oHNaeZ7x5Id4B66vUukflzxFGyuZ0XUWPCionlZiqzpZZspDrXbh
E4vY7Oe34PTvyUFMsu6jek7an8feJLQzyyFOjlKoYphEJbOoRl8ILoSsiQ6biMXq
6WGBwJIoPlJHTeclUdrknwG9hh/UC/VpCAQRJ1DWR6fdtiMHnbMQFwIDAQABo0Uw
QzAOBgNVHQ8BAf8EBAMCAQYwEgYDVR0TAQH/BAgwBgEB/wIBADAdBgNVHQ4EFgQU
IINnlemLChBaZ5urqj6LT9Ge27MwDQYJKoZIhvcNAQELBQADggIBANTf8EWOSyrn
gKbbJ/+i/+xRJLKW1TgPvp4o2ZpHHHeIjC9GNlo2iVVW+e2pjR+mkoMCGeUfp3aq
6KLb7YFoOWPFP8Qljlxlq/Eie5WS/EY/Mjuwu9cvteSaGCfkNSH7VMKMek8zn3nt
uHGGGoos2CxoylO4WDenSIP54XDvdVGJtD/a993GB5cK9TQBQu6iJd2eAgQ6XNbx
VvgyQXZC6Ex34Wedn10L1qzQxF+giY3HeW1fZkzeUi4W9DxSQRXg1F67aAGhyZsw
bx5x5SlV/RWE9uoAgR8cc0rUu0vyQo6CxIObxs/trYHzDrStds5PU6t88GBZmu7p
lrf/pd9FGLGG/BVFb8l11jjG5yxH7eB/I481EFfA/kiK2IsTyKqQKi0WhuTJlqOn
9oxkQFhLQ873BUh1r2Y0NvNovQzjPBzov0d5yE0rwfVU1r/Jnykhk/y6yhdLcN8W
PyoJfv+iTH4OqkxNlewAoAHZSTtpzHHjOncq2+Fdan9+qYJKpnhohL3FsLhgQIba
qSofdfoE6psXObhUCAh8vnrlLV1D7q7ec0kbVWqyjD52EOo0/YfI7rNz3XybuUny
9SF3I1SYnVNss/9rdOJnjxXt2J31VmDq2UwEb88G0FCGM9AdWor9r2tbfFptCQ49
Mde4KUGsJkICnXRYYzliNbRFzWx6AjNm
-----END CERTIFICATE-----
`)

func metricStoreCaCrtBytes() ([]byte, error) {
	return _metricStoreCaCrt, nil
}

func metricStoreCaCrt() (*asset, error) {
	bytes, err := metricStoreCaCrtBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "metric-store-ca.crt", size: 1777, mode: os.FileMode(0444), modTime: time.Unix(1695990541, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0xed, 0xf4, 0x67, 0xdc, 0xcd, 0x2c, 0x8c, 0x60, 0x0, 0x2a, 0xab, 0xe7, 0x27, 0x53, 0x9f, 0x1c, 0xdf, 0x27, 0xc0, 0xac, 0x74, 0xe4, 0xb8, 0xcd, 0x56, 0x4f, 0xd8, 0x94, 0x3d, 0xac, 0x68, 0x2f}}
	return a, nil
}

var _metricStoreCaKey = []byte(`-----BEGIN RSA PRIVATE KEY-----
MIIJKQIBAAKCAgEA5TeWdkisCT1nEE+QTFaBKp0YRpGVWZkZOvaPav/7t5hlhwMN
3N5ejvH4WQrsxS3XtrhDiz8PB+s3EYvrKc0ol4hKXyiM7mLGZjJG2maUJvzgfJAr
seQ1xIgRHqXFqQkDj8GqZIW5K6tb8+mlL03gQNpAJKbC4sqMlSV285E5fcdjQxgh
LeA5t0UXWntah51/Gc1EG8T+UzhYXIR1boae7wXmmWwuMTeJaZmCpmbbwpm33syI
xC1qksWzr8a+mIcKf+V7J/YrvmXkM8JrX113ohoSEnMiKVwNd76XKlsnePTUR89L
zLyoSmAo0B/Tf2y49GSs5z0w4b3EZL9VBbTUVWeoq/7XYry+NHv9jGU/49N+Ullf
VsPkEaegzVMA8UBBrfz7LUEXrMtfwn8gLCYaMvdh9/9L9KYBRpIok5SS5eBaW+W1
xwYrLlUB0iqbYfi/Pfx6JFbe7vaD4waXB0JcJFjSqf5S1tc9WTuppyoqHxL3/8TA
8Y6fVWtP97cbyyrAP6BzWnme8eSHeAeur1LpH5c8RRsrmdF1FjwoqJ5WYqs6WWbK
Q6124ROL2Oznt+D078lBTLLuo3pO2p/H3iS0M8shTo5SqGKYRCWzqEZfCC6ErIkO
m4jF6ulhgcCSKD5SR03nJVHa5J8BvYYf1Av1aQgEESdQ1ken3bYjB52zEBcCAwEA
AQKCAgAqfOdS/Z2GCO+1wknJHK/Mqln5mrrIZOycVV+4QcLzATiwkgxbyIxWituy
Bahl1F2L7RP4F7Q9j4ghpIHuuaywif7fLLES7xQ/lUo06ZbEs1MZQ9AVpWuiBmbF
+4xsDNOwLgHbqD3urlDZIZIQ9qp+2vXQ1WiCiXENpGgsNdsmSXNI2Iwt6MZKBnCR
wRPC15rbuYTKcPWDj4oxfAwYdLO5MqrP/ZGCZfz+qgnhtmc95yiCD/+5/YEnu6XX
C0wBEecMVglCGwt4u4JVZdBpWPX4AkUfTmAisoF8lMOIgmUKsrc2qGIwjTfUsYZf
LccSc6DFDHRQWLNa5MYmtqCX8jD5WdrGwvVzHiX0cB79Qoqa3QV+KV15qZe1Om7w
M2LYdfRG01I3ZPwdDM+5QdRdWexBA/TlDO3xqJXwL3mVOdtJ/Je5HaXDYqkOm1W7
sbFLDOIpxBQXkIesB9/DAvJSSrxRVNjZgDqHRVnkwZwKHbw7FL4suTeERh3gLXQM
vqCPFPyDWmHlfBvSnDoCo+XYk3VW6bhFsspwXAq+poUiVi79052nkc0I/5cdwG6P
NSvovXPZIWvZsdnKUMsMGj5FH6HaO+gT2Ae0ojc7pumwK4it1YL5e7sSZw4pSuse
Ckpbq7GM4QDllwtRctOnuIbLa6a1AhHsZJD//nhjNAA3KErQYQKCAQEA5zxmezC9
2QaiI8502tddb/MXHD/nkdgiQq7Z8ZTLzesNsnf/77zwJe1SAdkMx7pk49M5DwH2
qChcLIidvVdVwhF2fSKxirotjHxIIMONJjXqnRaFEcMRFdAPjlkoskIe/kw6tgAn
ZQkgrdRNnDFrITXr3TQLCGdHCMzb6XS5D4cCrYQf50elDlOFFclGQVo6FuUcffZT
iRaT709qrVvEZRRnAQbzhjbfdSCD1xekO81W+UipHF5qqYedcsFjGcS0LL5dD0jv
drkdCtrW22xdDrVhc/JNT33bbVJMe2CwOxwihRmyBKSmrfhjbEkIgGYvvrommOlC
uVMkgwbSlW7PPQKCAQEA/cPW9/jJZazlahD4UdmeFU/SUTE9poL7kmA8VHYYnfyr
FtGDUHAFNCPVhljs/0HRnL9csrEHYRHMMKawZQD7bTtfhW022oPxQ9YPZzg/aHgo
gRFGU7UvZjph3nY8XAmVDMKnvJA69GnJjLiG85SLdn6HEAGdqPyqQg3k3yiChYbH
+PowlS3wXZDHvw6JKDFdYwX+/iSaL9vMB9EMI1vPBm7gyqZXY6+qzkqiTc1sYLIf
EMW+hrocxozN9xyUNNnhRy2XNyUak8meVdMFZrcg1h64GfznQZ1bv2bE4InEbHf3
CxqxbWSX1nXz7uFqzwitV6QklQjRheS/AfqtDktR4wKCAQAFoK+x0dbdAE9T5cNs
TA+HGPh4BIojP4pd6xl8yq1HHrBfppIBCK0jjyoOx3SLK9smvE5IMjkJkKnln5GP
OR/qMDidBQojITLYl3G98mRuCKPkHNcyPngc+spWIY9e/0L3120aXtiWmelEscUN
xxofXcuWv5yBINpWuX2kqeWTHisPhAauv0yiE6BKjnJ6RrLhOcQ+wI756CXDjkA/
ZdtaxmtXWA73NkCr/hWXV4j0t6OlP4J2IUohRB6t200JJINqD1v+cjz5u7mcOQU/
o9yD7iAoDT6ab6q2d2lLG2hOl/mzGZP+ju9Ljp8E1KYzUclZr/gegpbQIdjio3je
kCrVAoIBAQCq2CBwDeS5OS+yuv4TTOlq+7RiyT3yTpjEMVosmt1z79nXoPJBQ0md
ksp8in30VAGlAAiOnTSUm4DW+EIlngWnwqNKlv6pGs9hlkoEeg/ma48JZfHtBTyG
HKQrO3rjk+fvEVYQUyH9zwLMZKcmckl6WzDfC9dzH7gYhHYj74gAEX+sFfSDWsxK
keCItmaM0r9GnZDQ1R+hPN8eHBWJ8JNuh1N724VWLbxW6lRfAQAIEaNsjVT6K26Y
Fc/MoEb/VfifDQiTLb245bJdoZYvUvcecMwNYwDmYeSU9cFyUg4V4KZHqY7uUR0Q
W5UArG5WOEdLi8y9MZSuChS2ZmgACaF1AoIBAQCEnlnt6f2/Hfvesf5VOwRc18JI
q53dCbdWk4EfwYc0KGo8qlNtiytDxnOJjTdyY5preqsWhud08maxpj6o4TBDPdW5
opVdMShImjeCGQRyrcUnTCT+I82fu1LUfkRRr3VgpiQukx0I1f0HVR7mXyXOV9hI
pE77cd22UYY8glExqLCFBN6+1tPnb6jm+E/75duyO7ygPhsnffs16Kmw8dhAPd7h
xeRKoy9K+T9AWhhzdrCk7jkIjb7FMIg4JOIUU2Sy8xej3snRJsGBLlvjLj2FoOtc
vU+RTnWALu/vou7dSh3e/fZ0Wozo/B504Mlq6B+Ox0yUr68ScfNCstXjHUzh
-----END RSA PRIVATE KEY-----
`)

func metricStoreCaKeyBytes() ([]byte, error) {
	return _metricStoreCaKey, nil
}

func metricStoreCaKey() (*asset, error) {
	bytes, err := metricStoreCaKeyBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "metric-store-ca.key", size: 3243, mode: os.FileMode(0440), modTime: time.Unix(1695990541, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0xac, 0x6a, 0xb4, 0x6a, 0xd1, 0x3f, 0xff, 0x15, 0x31, 0x88, 0x8e, 0xd8, 0xef, 0x6a, 0xe4, 0x61, 0xa3, 0xb8, 0x2f, 0x64, 0x3f, 0x25, 0xb7, 0x74, 0xfd, 0xb8, 0x71, 0xd5, 0xc0, 0xaf, 0x93, 0x98}}
	return a, nil
}

var _metricStoreCrt = []byte(`-----BEGIN CERTIFICATE-----
MIIERzCCAi+gAwIBAgIQIOFT5Fw8j2a1bva7aBKmPTANBgkqhkiG9w0BAQsFADAa
MRgwFgYDVQQDEw9tZXRyaWMtc3RvcmUtY2EwHhcNMjUwNTA4MDUyMjE2WhcNMjYx
MTA4MDUzMjE0WjAXMRUwEwYDVQQDEwxtZXRyaWMtc3RvcmUwggEiMA0GCSqGSIb3
DQEBAQUAA4IBDwAwggEKAoIBAQDEyPvBnSRwCMUHFIh9dow0PZ7RhY49AMtlOr3w
alu3gaQxHSEUp/756YdSGebZ79rYXQPr2nZH/8qhUtlZ7wbyHWkDRfKRgfxQecRs
mrp2DvdsqEq7i64rFhy6pRFNIhRTprELwnbocV0OERbvtdA27AZ9bGNtyuIX5hxL
EHfix2HFJiQYJfvusV/Sw7B8R9Z+nLSX6eQSGF4DfjIQ/Iy1IZhpFOd09kxeQMUp
KGLSDGFdfwuuLH9/eDahVy9I9iCnqHw8l93GEt3Fzx4gOBcC6dLzbopm7mSAoTfP
L9ruZiAxAQlZt+K7mZhlPZGmPZvn2oqqm7Wh8T0t1cW4Hlr1AgMBAAGjgYswgYgw
DgYDVR0PAQH/BAQDAgO4MB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAd
BgNVHQ4EFgQU/r07QR5jy4HkuvfL8BiUU/NHOvowHwYDVR0jBBgwFoAUIINnlemL
ChBaZ5urqj6LT9Ge27MwFwYDVR0RBBAwDoIMbWV0cmljLXN0b3JlMA0GCSqGSIb3
DQEBCwUAA4ICAQBGCAE+c7aCdI69qS3U9kZByDY4U2ZIfPc2Gd90u6OMrASiLNA/
XUCKWEEL0D/09H3uhWkVPOoREbaoyiGPF51H5VSU4+kk+pJ225Gd6gHU1ybQS/3/
kFe0K6sMclUMBzucn+ve1XezruDRuVUghBPGxYFrmGt/A1jWDwZpjxI/AqgTrz/9
anaI5G/uaLI4Zakqt1FkrtBDQ/vio/R2IO/pnmWTyfLR0mchdLZ4UhBYr83scYc1
PHgXgIZkDznRN/4akPos7s94TOMEzpuMR0Td2V/i+xmsy7fkq4mfx+74QtFC4GUY
/Mp2YCDmzBVRhrJMTwQSiC3s/mia1SZIEMBJCc0ndBW3B69Ah5QOhZPqe4S5P/u/
Q0IpvidmZrNAmMESI6/F7bu+jzZapDRHjUz3JOcqTDUqGSCrzeHE3n+JjAkshm7w
Aao5pjhMY97da9uhyHn3jbhPL3euA0mSqdbVoyv2pkf7eX/ljtlymxYEEVLTzDe5
Ja4+71Y8W1FTB/VjuejGw2xo3GQWDPgt22BGcLHFPcwL380h6WaZ2gceyULMGi0w
YembtJhRjUTY+CFUGYIJP/Jt8w6aojGYOO1cb375lEeTd0GsVPSMyCykPP91Tl+K
URGCeB+C3VFhGvZ966zVh53kxWB5WIMRlEwXJy9z0BWuOpd9k5p6XzsVYg==
-----END CERTIFICATE-----
`)

func metricStoreCrtBytes() ([]byte, error) {
	return _metricStoreCrt, nil
}

func metricStoreCrt() (*asset, error) {
	bytes, err := metricStoreCrtBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "metric-store.crt", size: 1545, mode: os.FileMode(0444), modTime: time.Unix(1695990542, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0xa0, 0x9f, 0xf1, 0xbd, 0xb8, 0x61, 0x7e, 0x7b, 0x79, 0xa2, 0x64, 0xb6, 0x9, 0x92, 0x74, 0xfb, 0x87, 0xeb, 0xfa, 0x1d, 0x90, 0x7a, 0xda, 0x75, 0x8b, 0x38, 0xd2, 0x51, 0x5, 0xc6, 0xfd, 0x99}}
	return a, nil
}

var _metricStoreCsr = []byte(`-----BEGIN CERTIFICATE REQUEST-----
MIIChjCCAW4CAQAwFzEVMBMGA1UEAxMMbWV0cmljLXN0b3JlMIIBIjANBgkqhkiG
9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxMj7wZ0kcAjFBxSIfXaMND2e0YWOPQDLZTq9
8Gpbt4GkMR0hFKf++emHUhnm2e/a2F0D69p2R//KoVLZWe8G8h1pA0XykYH8UHnE
bJq6dg73bKhKu4uuKxYcuqURTSIUU6axC8J26HFdDhEW77XQNuwGfWxjbcriF+Yc
SxB34sdhxSYkGCX77rFf0sOwfEfWfpy0l+nkEhheA34yEPyMtSGYaRTndPZMXkDF
KShi0gxhXX8Lrix/f3g2oVcvSPYgp6h8PJfdxhLdxc8eIDgXAunS826KZu5kgKE3
zy/a7mYgMQEJWbfiu5mYZT2Rpj2b59qKqpu1ofE9LdXFuB5a9QIDAQABoCowKAYJ
KoZIhvcNAQkOMRswGTAXBgNVHREEEDAOggxtZXRyaWMtc3RvcmUwDQYJKoZIhvcN
AQELBQADggEBAKwV7MZezSUI0aIdPI3W9/pJme097OcOObnUVhVztm/1PyjDoBIH
duKFTTtcfn8GgVyhNhti/JZEhlQUwL1LP6mMjZTwFRPNAARV1CosspqsA3gZl4Rk
BJlATugJ/iJKc/fpjUxkryhAq+gklBm3s80u8vf628XWn0FvNMhtG+02lf4u5Obg
p0JkUvxgOHei6AmsSdBbAM4eRO1Ie3CGJh/9LTmp9Qg9vktvHPY1Tin2JX9mgIEO
wkKAx7QGD03cnbqX+VOX1OS1foy/H+Bt20VSWGY1Fqw5iNZbpQBKxCxFdjqtuGyM
S2BLrwc/dL/apjzgtS2V72vz84xtiZG92ww=
-----END CERTIFICATE REQUEST-----
`)

func metricStoreCsrBytes() ([]byte, error) {
	return _metricStoreCsr, nil
}

func metricStoreCsr() (*asset, error) {
	bytes, err := metricStoreCsrBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "metric-store.csr", size: 952, mode: os.FileMode(0444), modTime: time.Unix(1695990542, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0x14, 0x74, 0xfc, 0x2d, 0x3e, 0x50, 0x43, 0xed, 0x86, 0x54, 0xc1, 0xf9, 0x9, 0x28, 0x17, 0xdc, 0x91, 0xab, 0x7a, 0x22, 0xfd, 0xb0, 0x65, 0x81, 0x84, 0xe4, 0x80, 0x34, 0xf, 0x69, 0x7a, 0x19}}
	return a, nil
}

var _metricStoreKey = []byte(`-----BEGIN RSA PRIVATE KEY-----
MIIEpQIBAAKCAQEAxMj7wZ0kcAjFBxSIfXaMND2e0YWOPQDLZTq98Gpbt4GkMR0h
FKf++emHUhnm2e/a2F0D69p2R//KoVLZWe8G8h1pA0XykYH8UHnEbJq6dg73bKhK
u4uuKxYcuqURTSIUU6axC8J26HFdDhEW77XQNuwGfWxjbcriF+YcSxB34sdhxSYk
GCX77rFf0sOwfEfWfpy0l+nkEhheA34yEPyMtSGYaRTndPZMXkDFKShi0gxhXX8L
rix/f3g2oVcvSPYgp6h8PJfdxhLdxc8eIDgXAunS826KZu5kgKE3zy/a7mYgMQEJ
Wbfiu5mYZT2Rpj2b59qKqpu1ofE9LdXFuB5a9QIDAQABAoIBAQC1KAD74Fom+SvI
tNJiDbxMa13FrJmg9xZHfqhUptUAPkyVGifWCEHmd2Gn50hp4TEqdZaijV7OMWCs
2sRU0oMmaITACqif43YP78kv4dE91dFZKiSCOrh/2b9g44zl4TWtPItINCGbIqFz
za+7xTiFFwtyc1GlRVyWe7QYNnTnQt/T/JzDwX0AJ1HXfsgR6VchMiIaDL4NBdcS
+fSSwEXhDZrMC8EVf4I/nLLQa7so2MtmbBlEA/OgtHbpbDQeuUxS+vFrknoIvR0H
KTMDE56jNYglRHSya97MM7JT+8v0wSY6Pvxpdfi5R41xImbPGRwjEZCDQ+mmHCPP
CsOHHN8RAoGBAOokB4dYDYDBchOLHUMW9caBZlslOivw2qRqFsIJaFEKmEkasnAd
bNc+2O+KyHr/SWLMa5IOQMrWaV9bsacEXkKINgx+2XsVxLP3CTfUWP4LNKwazfjY
wLITYV7KsVDv9b+imWUbz+mZd7jJVe/ELxeUmVK4GZv9DatinuzE+kVnAoGBANco
JyV7Nez42dw/bsIwTwUZS/4d6ZQ1QKB+Oe+CSda9lPzYds/McVceW5Y4fk43qjaQ
KWNj0KcUU0srxFTPpRxGn4xhaZDbn5dQkjmurPg/xfDGrzmFwfLjkqWkdBWGSMAH
0qBjGa1WEVjxvJb2k71ARaIbu7OpyValsYyu6KdDAoGBAMYUEvZyDIJXpP1ZnDjM
rMHxaLlFBjB0Q1QCmBwxPzoIP4rg9gIZMqHp/jawbyh23guiKoLWYgP3Xg+ZD/Le
pCue9jKeAbi6Ur15CShdEahhrH7I8mVKYcKE2MQLr/Rr/LfRg/ngjITwGzONyJDd
pIVLZmZvbuLjMvRBq3dcsOmTAoGBALQ4JuonVVkkbOAmpfC0pEviD5xQk+mX3YVR
lde/63ebHyPXcVXHqpxNimu+8FU2HTZM9M4SuqBozwglJfPgZi3UHippIhK7U+dc
Ds+QN8RNLtDqq7VkC7wW0Sw8Hxw0edWX995uhACEGk3FVrGg4slf/7O0xTnNmx8f
9SOhErGfAoGAJRkk3o0ikxWk6axHQb/YqSmkvBOD5NcXSlZK3U+Pnho3NM/ezwSv
o2ZCAvvDIDUIl7VTr2xzSWmxXMpLDEYPylN41cz5sgl7zidjWbHqyVaRSELf/Bzu
M+sDBamnTblT6CLSwsZ8TUBQcQyygfWxGFw6dwJJz7atBUv+0HM4zGc=
-----END RSA PRIVATE KEY-----
`)

func metricStoreKeyBytes() ([]byte, error) {
	return _metricStoreKey, nil
}

func metricStoreKey() (*asset, error) {
	bytes, err := metricStoreKeyBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "metric-store.key", size: 1679, mode: os.FileMode(0440), modTime: time.Unix(1695990542, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0xf, 0x69, 0x50, 0xca, 0x5d, 0xc8, 0x51, 0x35, 0x77, 0x6e, 0x3c, 0xc6, 0xf0, 0x9f, 0xa9, 0x2d, 0x77, 0x0, 0xb8, 0xfe, 0xf, 0x7e, 0x8f, 0x87, 0x13, 0x43, 0x53, 0x73, 0x19, 0xf9, 0x2d, 0x63}}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// AssetString returns the asset contents as a string (instead of a []byte).
func AssetString(name string) (string, error) {
	data, err := Asset(name)
	return string(data), err
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// MustAssetString is like AssetString but panics when Asset would return an
// error. It simplifies safe initialization of global variables.
func MustAssetString(name string) string {
	return string(MustAsset(name))
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetDigest returns the digest of the file with the given name. It returns an
// error if the asset could not be found or the digest could not be loaded.
func AssetDigest(name string) ([sha256.Size]byte, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return [sha256.Size]byte{}, fmt.Errorf("AssetDigest %s can't read by error: %v", name, err)
		}
		return a.digest, nil
	}
	return [sha256.Size]byte{}, fmt.Errorf("AssetDigest %s not found", name)
}

// Digests returns a map of all known files and their checksums.
func Digests() (map[string][sha256.Size]byte, error) {
	mp := make(map[string][sha256.Size]byte, len(_bindata))
	for name := range _bindata {
		a, err := _bindata[name]()
		if err != nil {
			return nil, err
		}
		mp[name] = a.digest
	}
	return mp, nil
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"metric-store-ca.crl": metricStoreCaCrl,
	"metric-store-ca.crt": metricStoreCaCrt,
	"metric-store-ca.key": metricStoreCaKey,
	"metric-store.crt":    metricStoreCrt,
	"metric-store.csr":    metricStoreCsr,
	"metric-store.key":    metricStoreKey,
}

// AssetDebug is true if the assets were built with the debug flag enabled.
const AssetDebug = false

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//
//	data/
//	  foo.txt
//	  img/
//	    a.png
//	    b.png
//
// then AssetDir("data") would return []string{"foo.txt", "img"},
// AssetDir("data/img") would return []string{"a.png", "b.png"},
// AssetDir("foo.txt") and AssetDir("notexist") would return an error, and
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		canonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(canonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}

var _bintree = &bintree{nil, map[string]*bintree{
	"metric-store-ca.crl": {metricStoreCaCrl, map[string]*bintree{}},
	"metric-store-ca.crt": {metricStoreCaCrt, map[string]*bintree{}},
	"metric-store-ca.key": {metricStoreCaKey, map[string]*bintree{}},
	"metric-store.crt":    {metricStoreCrt, map[string]*bintree{}},
	"metric-store.csr":    {metricStoreCsr, map[string]*bintree{}},
	"metric-store.key":    {metricStoreKey, map[string]*bintree{}},
}}

// RestoreAsset restores an asset under the given directory.
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = os.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	return os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
}

// RestoreAssets restores an asset under the given directory recursively.
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(canonicalName, "/")...)...)
}
