#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $DIR/shared

echo "-- BOSH create-release"
prep_src

git rev-parse HEAD > oss_sha
cat oss_sha

bosh create-release --force

cleanup
rm -f oss_sha
