#!/usr/bin/env bash

SCRIPT_DIR=$(cd $(dirname $0) && pwd)

if [ -z "${OM_TARGET}" ] || [ -z "${OM_USERNAME}" ] || [ -z "${OM_PASSWORD}" ]; then
  echo "OM_TARGET, OM_USERNAME, and OM_PASSWORD must be set"
  return
fi

echo "Configuring $OM_TARGET"

CERTS_DIR=$SCRIPT_DIR/certs
mkdir $CERTS_DIR
CERT_NAME=".properties.otel_provider_mtls" PRODUCT="metric-store"

function get-certs() {
  echo "Getting $PRODUCT cert of $CERT_NAME"
  export KEY_FILE=$CERTS_DIR/key.pem
  om -k credentials -p ${PRODUCT} -c ${CERT_NAME} -f private_key_pem > "${KEY_FILE}"

  export CERT_FILE=$CERTS_DIR/cert.pem
  om -k credentials -p ${PRODUCT} -c ${CERT_NAME} -f cert_pem > "${CERT_FILE}"
}

export SYS_DOMAIN=$(cat "${ENVIRONMENT_LOCK_METADATA}" | jq -r .sys_domain)
ca_cert="$(om certificate-authorities -f json | jq '.[0].cert_pem')"
export CA_FILE=$CERTS_DIR/ca_cert.pem
cat "${ca_cert}" > $CA_FILE

PRODUCT="metric-store" CERT_NAME=".properties.otel_provider_mtls" get-certs
ms_private_key_pem="$(awk '{printf "%s\\n", $0}' ${KEY_FILE} )"
ms_cert_pem="$(awk '{printf "%s\\n", $0}' ${CERT_FILE} )"

PRODUCT="p-healthwatch2" CERT_NAME=".properties.healthwatch_exporter_client_mtls" get-certs
hw_private_key_pem="$(awk '{printf "%s\\n", $0}' ${KEY_FILE} )"
hw_cert_pem="$(awk '{printf "%s\\n", $0}' ${CERT_FILE} )"

# curl --cert "${CERT_FILE}" --key "${KEY_FILE}" --cacert "${CA_FILE}"
cat <<-HEREDOC > otel-config.yaml
---
product-name: cf
product-properties:
  .properties.otel_collector_metric_exporters_config:
    value: |-
      prometheus:
        endpoint: ":53035"
        add_metric_suffixes: false
        tls:
          ca_pem: ${ca_cert}
          cert_pem: "${hw_cert_pem}"
          key_pem: "${hw_private_key_pem}"
      otlp:
        endpoint: dns:metric-store.service.internal:6062
        tls:
          insecure_skip_verify: true
          ca_pem: ${ca_cert}
          cert_pem: "${ms_cert_pem}"
          key_pem: "${ms_private_key_pem}"
HEREDOC

echo "CF Config"
echo "==================================="
cat otel-config.yaml
echo "==================================="
om configure-product -p cf -c otel-config.yaml && om apply-changes --product-name cf
