#!/bin/bash

PROJECT_DIR="$(cd "$(dirname "$0")/.."; pwd)"
PROJECT_SRC_DIR=src/github.com/cloudfoundry/metric-store-release

pushd $PROJECT_DIR
  go mod vendor

  # put go source files in src directory so go build is pleased.
  mkdir -p ${PROJECT_DIR}/${PROJECT_SRC_DIR}/src/{cmd,pkg}
  cp -r vendor/* ${PROJECT_DIR}/src/
  cp -r ${PROJECT_DIR}/src/cmd ${PROJECT_DIR}/${PROJECT_SRC_DIR}/src
  cp -r ${PROJECT_DIR}/src/pkg ${PROJECT_DIR}/${PROJECT_SRC_DIR}/src

  bosh create-release --force

  chmod 777 ${PROJECT_SRC_DIR}
  find ${PROJECT_DIR}/src/ -mindepth 1 -maxdepth 1 -not -name 'pkg' -not -name 'cmd' -not -name 'api' -not -name 'internal' -print0 | xargs -0 rm -rf --

  go mod tidy
popd
