#!/bin/bash

set -exu

cd ~/workspace/denver-locks
set +x
    source ~/workspace/denver-bash-it/custom/environment-targeting.bash
set -x

bosh-target yuzu

# Check that we're connected to bosh
bosh environment > /dev/null

# run metric-store-smoke-tests errand
bosh -d cf run-errand metric-store-smoke-tests

