name: metric_store_config
label: Metric Store Configuration
description: Metric Store Configuration
property_inputs:
  - reference: .properties.replication_factor
    label: Replication Factor
    description: How many instances should store a copy of each metric (*NOTE* Increasing this value will effect availabilty of historical metrics and increase storage needed going forward)
  - reference: .properties.max_concurrent_queries
    label: Max Concurrent Queries
    description: Queue queries after this maximum number of queries running concurrently per node
  - reference: .properties.enable_envelope_selector
    label: Only store Application Metrics
    description: If enabled, only envelopes with application specific tags, app_id and applicationGuid, will be kept.
  - reference: .properties.use_otel_for_metrics_collection
    label: Use Open Telemetry for Metrics Collection
    description: Use Open Telemetry for Metrics Collection instead of the firehose. Requires TAS 7+
