name: Auto Merge Pull Requests
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  status: {}
jobs:
  auto-merge-job:
    name: Vendor, Test and Merge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.14.7'
        id: go
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Vendor Dependencies
        run: |
          go mod tidy
          go mod vendor
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to commit"
          else
            git add -A
            git config --global user.name "Metric Store Bot"
            git config --global user.email "cf-log-cache+github@pivotal.io"
            git commit -m "Updating vendored dependencies"
            git push
          fi
      - name: Run Tests
        run: |
          echo "Git HEAD at:"
          git rev-parse HEAD
          go mod vendor
          ./scripts/test unit
      - name: Merge
        uses: "pascalgn/automerge-action@fc8281547d24638fac1e4149bbde710cced773d1"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "auto-merge"
          MERGE_DELETE_BRANCH: true
          MERGE_RETRIES: 60
          MERGE_RETRY_SLEEP: 10000
          MERGE_METHOD: "rebase"
          MERGE_FORKS: false
