name: Auto Merge Pull Requests
on:
  pull_request:
    types:
      - labeled
jobs:
  auto-merge-job:
    name: Merge PR
    runs-on: ubuntu-latest
    steps:
      - name: Merge
        uses: "pascalgn/automerge-action@fc8281547d24638fac1e4149bbde710cced773d1"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "auto-merge,tests-passed"
          MERGE_DELETE_BRANCH: true
          MERGE_RETRIES: 60
          MERGE_RETRY_SLEEP: 10000
          MERGE_METHOD: "rebase"
          MERGE_FORKS: false
