name: Check and Remove Label

on:
  issues:
    types:
      - labeled

jobs:
  check_and_remove_label:
    runs-on: ubuntu-latest

    steps:
      - name: Check if label exists and remove it
        id: check_label
        run: |
          if [[ $(jq -e '.issue.labels != null' $GITHUB_EVENT_PATH) == "true" ]]; then
            if [[ $(jq -r '.issue.labels[] | select(.name=="tests-passed") | .name' $GITHUB_EVENT_PATH) == "tests-passed" ]]; then
              echo "Removing label..."
              # Perform your desired action here
            else
              echo "Label not found. No action required."
            fi
          else
            echo "No labels found on the issue. No action required."
          fi
