name: Test Everything
on:
  pull_request:
jobs:
  label:
    name: Run only when the labels do not include "dependencies"
    if: ${{ contains(github.event.pull_request.labels.*.names, 'tests-passed') }}
    runs-on: ubuntu-latest
    steps:
      - name: debug
        run: |
          echo "${{ toJson(github.event.pull_request.labels) }}"
          echo "${{ toJson(github.event.pull_request.labels.*.names) }}"
          github.issues.removeLabel({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            name: 'tests-passed'
          }
  test-job:
    name: All Tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.20.4'
        id: go
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Run Tests
        run: |
          echo "Git HEAD at: $(git rev-parse HEAD)"
          ./scripts/test || ./scripts/test || ./scripts/test
  success-job:
    needs: test-job
    name: Add Label
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['tests-passed']
            })
