name: Test Everything
on:
  pull_request:

jobs:
  test-job:
    name: All Tests
    runs-on: ubuntu-latest
    steps:
      - name: Run GitHub Script
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log("github.context", github.context);
