// Code generated by protoc-gen-go. DO NOT EDIT.
// source: promql.proto

package metricstore_v1

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PromQL struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PromQL) Reset()         { *m = PromQL{} }
func (m *PromQL) String() string { return proto.CompactTextString(m) }
func (*PromQL) ProtoMessage()    {}
func (*PromQL) Descriptor() ([]byte, []int) {
	return fileDescriptor_0808f1dc738840d6, []int{0}
}

func (m *PromQL) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PromQL.Unmarshal(m, b)
}
func (m *PromQL) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PromQL.Marshal(b, m, deterministic)
}
func (m *PromQL) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PromQL.Merge(m, src)
}
func (m *PromQL) XXX_Size() int {
	return xxx_messageInfo_PromQL.Size(m)
}
func (m *PromQL) XXX_DiscardUnknown() {
	xxx_messageInfo_PromQL.DiscardUnknown(m)
}

var xxx_messageInfo_PromQL proto.InternalMessageInfo

type PromQL_InstantQueryRequest struct {
	Query                string   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Time                 string   `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PromQL_InstantQueryRequest) Reset()         { *m = PromQL_InstantQueryRequest{} }
func (m *PromQL_InstantQueryRequest) String() string { return proto.CompactTextString(m) }
func (*PromQL_InstantQueryRequest) ProtoMessage()    {}
func (*PromQL_InstantQueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0808f1dc738840d6, []int{0, 0}
}

func (m *PromQL_InstantQueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PromQL_InstantQueryRequest.Unmarshal(m, b)
}
func (m *PromQL_InstantQueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PromQL_InstantQueryRequest.Marshal(b, m, deterministic)
}
func (m *PromQL_InstantQueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PromQL_InstantQueryRequest.Merge(m, src)
}
func (m *PromQL_InstantQueryRequest) XXX_Size() int {
	return xxx_messageInfo_PromQL_InstantQueryRequest.Size(m)
}
func (m *PromQL_InstantQueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PromQL_InstantQueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PromQL_InstantQueryRequest proto.InternalMessageInfo

func (m *PromQL_InstantQueryRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *PromQL_InstantQueryRequest) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

type PromQL_RangeQueryRequest struct {
	Query                string   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Start                string   `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	End                  string   `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
	Step                 string   `protobuf:"bytes,4,opt,name=step,proto3" json:"step,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PromQL_RangeQueryRequest) Reset()         { *m = PromQL_RangeQueryRequest{} }
func (m *PromQL_RangeQueryRequest) String() string { return proto.CompactTextString(m) }
func (*PromQL_RangeQueryRequest) ProtoMessage()    {}
func (*PromQL_RangeQueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0808f1dc738840d6, []int{0, 1}
}

func (m *PromQL_RangeQueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PromQL_RangeQueryRequest.Unmarshal(m, b)
}
func (m *PromQL_RangeQueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PromQL_RangeQueryRequest.Marshal(b, m, deterministic)
}
func (m *PromQL_RangeQueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PromQL_RangeQueryRequest.Merge(m, src)
}
func (m *PromQL_RangeQueryRequest) XXX_Size() int {
	return xxx_messageInfo_PromQL_RangeQueryRequest.Size(m)
}
func (m *PromQL_RangeQueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PromQL_RangeQueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PromQL_RangeQueryRequest proto.InternalMessageInfo

func (m *PromQL_RangeQueryRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *PromQL_RangeQueryRequest) GetStart() string {
	if m != nil {
		return m.Start
	}
	return ""
}

func (m *PromQL_RangeQueryRequest) GetEnd() string {
	if m != nil {
		return m.End
	}
	return ""
}

func (m *PromQL_RangeQueryRequest) GetStep() string {
	if m != nil {
		return m.Step
	}
	return ""
}

type PromQL_SeriesQueryRequest struct {
	Match                []string `protobuf:"bytes,1,rep,name=match,json=match[],proto3" json:"match,omitempty"`
	Start                string   `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	End                  string   `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PromQL_SeriesQueryRequest) Reset()         { *m = PromQL_SeriesQueryRequest{} }
func (m *PromQL_SeriesQueryRequest) String() string { return proto.CompactTextString(m) }
func (*PromQL_SeriesQueryRequest) ProtoMessage()    {}
func (*PromQL_SeriesQueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0808f1dc738840d6, []int{0, 2}
}

func (m *PromQL_SeriesQueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PromQL_SeriesQueryRequest.Unmarshal(m, b)
}
func (m *PromQL_SeriesQueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PromQL_SeriesQueryRequest.Marshal(b, m, deterministic)
}
func (m *PromQL_SeriesQueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PromQL_SeriesQueryRequest.Merge(m, src)
}
func (m *PromQL_SeriesQueryRequest) XXX_Size() int {
	return xxx_messageInfo_PromQL_SeriesQueryRequest.Size(m)
}
func (m *PromQL_SeriesQueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PromQL_SeriesQueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PromQL_SeriesQueryRequest proto.InternalMessageInfo

func (m *PromQL_SeriesQueryRequest) GetMatch() []string {
	if m != nil {
		return m.Match
	}
	return nil
}

func (m *PromQL_SeriesQueryRequest) GetStart() string {
	if m != nil {
		return m.Start
	}
	return ""
}

func (m *PromQL_SeriesQueryRequest) GetEnd() string {
	if m != nil {
		return m.End
	}
	return ""
}

type PromQL_LabelsQueryRequest struct {
	LocalOnly            bool     `protobuf:"varint,1,opt,name=local_only,json=localOnly,proto3" json:"local_only,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PromQL_LabelsQueryRequest) Reset()         { *m = PromQL_LabelsQueryRequest{} }
func (m *PromQL_LabelsQueryRequest) String() string { return proto.CompactTextString(m) }
func (*PromQL_LabelsQueryRequest) ProtoMessage()    {}
func (*PromQL_LabelsQueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0808f1dc738840d6, []int{0, 3}
}

func (m *PromQL_LabelsQueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PromQL_LabelsQueryRequest.Unmarshal(m, b)
}
func (m *PromQL_LabelsQueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PromQL_LabelsQueryRequest.Marshal(b, m, deterministic)
}
func (m *PromQL_LabelsQueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PromQL_LabelsQueryRequest.Merge(m, src)
}
func (m *PromQL_LabelsQueryRequest) XXX_Size() int {
	return xxx_messageInfo_PromQL_LabelsQueryRequest.Size(m)
}
func (m *PromQL_LabelsQueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PromQL_LabelsQueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PromQL_LabelsQueryRequest proto.InternalMessageInfo

func (m *PromQL_LabelsQueryRequest) GetLocalOnly() bool {
	if m != nil {
		return m.LocalOnly
	}
	return false
}

type PromQL_LabelValuesQueryRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	LocalOnly            bool     `protobuf:"varint,2,opt,name=local_only,json=localOnly,proto3" json:"local_only,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PromQL_LabelValuesQueryRequest) Reset()         { *m = PromQL_LabelValuesQueryRequest{} }
func (m *PromQL_LabelValuesQueryRequest) String() string { return proto.CompactTextString(m) }
func (*PromQL_LabelValuesQueryRequest) ProtoMessage()    {}
func (*PromQL_LabelValuesQueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0808f1dc738840d6, []int{0, 4}
}

func (m *PromQL_LabelValuesQueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PromQL_LabelValuesQueryRequest.Unmarshal(m, b)
}
func (m *PromQL_LabelValuesQueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PromQL_LabelValuesQueryRequest.Marshal(b, m, deterministic)
}
func (m *PromQL_LabelValuesQueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PromQL_LabelValuesQueryRequest.Merge(m, src)
}
func (m *PromQL_LabelValuesQueryRequest) XXX_Size() int {
	return xxx_messageInfo_PromQL_LabelValuesQueryRequest.Size(m)
}
func (m *PromQL_LabelValuesQueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PromQL_LabelValuesQueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PromQL_LabelValuesQueryRequest proto.InternalMessageInfo

func (m *PromQL_LabelValuesQueryRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PromQL_LabelValuesQueryRequest) GetLocalOnly() bool {
	if m != nil {
		return m.LocalOnly
	}
	return false
}

type PromQL_InstantQueryResult struct {
	// Types that are valid to be assigned to Result:
	//	*PromQL_InstantQueryResult_Scalar
	//	*PromQL_InstantQueryResult_Vector
	//	*PromQL_InstantQueryResult_Matrix
	Result               isPromQL_InstantQueryResult_Result `protobuf_oneof:"Result"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *PromQL_InstantQueryResult) Reset()         { *m = PromQL_InstantQueryResult{} }
func (m *PromQL_InstantQueryResult) String() string { return proto.CompactTextString(m) }
func (*PromQL_InstantQueryResult) ProtoMessage()    {}
func (*PromQL_InstantQueryResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_0808f1dc738840d6, []int{0, 5}
}

func (m *PromQL_InstantQueryResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PromQL_InstantQueryResult.Unmarshal(m, b)
}
func (m *PromQL_InstantQueryResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PromQL_InstantQueryResult.Marshal(b, m, deterministic)
}
func (m *PromQL_InstantQueryResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PromQL_InstantQueryResult.Merge(m, src)
}
func (m *PromQL_InstantQueryResult) XXX_Size() int {
	return xxx_messageInfo_PromQL_InstantQueryResult.Size(m)
}
func (m *PromQL_InstantQueryResult) XXX_DiscardUnknown() {
	xxx_messageInfo_PromQL_InstantQueryResult.DiscardUnknown(m)
}

var xxx_messageInfo_PromQL_InstantQueryResult proto.InternalMessageInfo

type isPromQL_InstantQueryResult_Result interface {
	isPromQL_InstantQueryResult_Result()
}

type PromQL_InstantQueryResult_Scalar struct {
	Scalar *PromQL_Point `protobuf:"bytes,1,opt,name=scalar,proto3,oneof"`
}

type PromQL_InstantQueryResult_Vector struct {
	Vector *PromQL_Vector `protobuf:"bytes,2,opt,name=vector,proto3,oneof"`
}

type PromQL_InstantQueryResult_Matrix struct {
	Matrix *PromQL_Matrix `protobuf:"bytes,3,opt,name=matrix,proto3,oneof"`
}

func (*PromQL_InstantQueryResult_Scalar) isPromQL_InstantQueryResult_Result() {}

func (*PromQL_InstantQueryResult_Vector) isPromQL_InstantQueryResult_Result() {}

func (*PromQL_InstantQueryResult_Matrix) isPromQL_InstantQueryResult_Result() {}

func (m *PromQL_InstantQueryResult) GetResult() isPromQL_InstantQueryResult_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *PromQL_InstantQueryResult) GetScalar() *PromQL_Point {
	if x, ok := m.GetResult().(*PromQL_InstantQueryResult_Scalar); ok {
		return x.Scalar
	}
	return nil
}

func (m *PromQL_InstantQueryResult) GetVector() *PromQL_Vector {
	if x, ok := m.GetResult().(*PromQL_InstantQueryResult_Vector); ok {
		return x.Vector
	}
	return nil
}

func (m *PromQL_InstantQueryResult) GetMatrix() *PromQL_Matrix {
	if x, ok := m.GetResult().(*PromQL_InstantQueryResult_Matrix); ok {
		return x.Matrix
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*PromQL_InstantQueryResult) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*PromQL_InstantQueryResult_Scalar)(nil),
		(*PromQL_InstantQueryResult_Vector)(nil),
		(*PromQL_InstantQueryResult_Matrix)(nil),
	}
}

type PromQL_RangeQueryResult struct {
	// Types that are valid to be assigned to Result:
	//	*PromQL_RangeQueryResult_Matrix
	Result               isPromQL_RangeQueryResult_Result `protobuf_oneof:"Result"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *PromQL_RangeQueryResult) Reset()         { *m = PromQL_RangeQueryResult{} }
func (m *PromQL_RangeQueryResult) String() string { return proto.CompactTextString(m) }
func (*PromQL_RangeQueryResult) ProtoMessage()    {}
func (*PromQL_RangeQueryResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_0808f1dc738840d6, []int{0, 6}
}

func (m *PromQL_RangeQueryResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PromQL_RangeQueryResult.Unmarshal(m, b)
}
func (m *PromQL_RangeQueryResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PromQL_RangeQueryResult.Marshal(b, m, deterministic)
}
func (m *PromQL_RangeQueryResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PromQL_RangeQueryResult.Merge(m, src)
}
func (m *PromQL_RangeQueryResult) XXX_Size() int {
	return xxx_messageInfo_PromQL_RangeQueryResult.Size(m)
}
func (m *PromQL_RangeQueryResult) XXX_DiscardUnknown() {
	xxx_messageInfo_PromQL_RangeQueryResult.DiscardUnknown(m)
}

var xxx_messageInfo_PromQL_RangeQueryResult proto.InternalMessageInfo

type isPromQL_RangeQueryResult_Result interface {
	isPromQL_RangeQueryResult_Result()
}

type PromQL_RangeQueryResult_Matrix struct {
	Matrix *PromQL_Matrix `protobuf:"bytes,1,opt,name=matrix,proto3,oneof"`
}

func (*PromQL_RangeQueryResult_Matrix) isPromQL_RangeQueryResult_Result() {}

func (m *PromQL_RangeQueryResult) GetResult() isPromQL_RangeQueryResult_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *PromQL_RangeQueryResult) GetMatrix() *PromQL_Matrix {
	if x, ok := m.GetResult().(*PromQL_RangeQueryResult_Matrix); ok {
		return x.Matrix
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*PromQL_RangeQueryResult) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*PromQL_RangeQueryResult_Matrix)(nil),
	}
}

type PromQL_SeriesQueryResult struct {
	Series               []*PromQL_SeriesInfo `protobuf:"bytes,1,rep,name=series,proto3" json:"series,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PromQL_SeriesQueryResult) Reset()         { *m = PromQL_SeriesQueryResult{} }
func (m *PromQL_SeriesQueryResult) String() string { return proto.CompactTextString(m) }
func (*PromQL_SeriesQueryResult) ProtoMessage()    {}
func (*PromQL_SeriesQueryResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_0808f1dc738840d6, []int{0, 7}
}

func (m *PromQL_SeriesQueryResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PromQL_SeriesQueryResult.Unmarshal(m, b)
}
func (m *PromQL_SeriesQueryResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PromQL_SeriesQueryResult.Marshal(b, m, deterministic)
}
func (m *PromQL_SeriesQueryResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PromQL_SeriesQueryResult.Merge(m, src)
}
func (m *PromQL_SeriesQueryResult) XXX_Size() int {
	return xxx_messageInfo_PromQL_SeriesQueryResult.Size(m)
}
func (m *PromQL_SeriesQueryResult) XXX_DiscardUnknown() {
	xxx_messageInfo_PromQL_SeriesQueryResult.DiscardUnknown(m)
}

var xxx_messageInfo_PromQL_SeriesQueryResult proto.InternalMessageInfo

func (m *PromQL_SeriesQueryResult) GetSeries() []*PromQL_SeriesInfo {
	if m != nil {
		return m.Series
	}
	return nil
}

type PromQL_LabelsQueryResult struct {
	Labels               []string `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PromQL_LabelsQueryResult) Reset()         { *m = PromQL_LabelsQueryResult{} }
func (m *PromQL_LabelsQueryResult) String() string { return proto.CompactTextString(m) }
func (*PromQL_LabelsQueryResult) ProtoMessage()    {}
func (*PromQL_LabelsQueryResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_0808f1dc738840d6, []int{0, 8}
}

func (m *PromQL_LabelsQueryResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PromQL_LabelsQueryResult.Unmarshal(m, b)
}
func (m *PromQL_LabelsQueryResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PromQL_LabelsQueryResult.Marshal(b, m, deterministic)
}
func (m *PromQL_LabelsQueryResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PromQL_LabelsQueryResult.Merge(m, src)
}
func (m *PromQL_LabelsQueryResult) XXX_Size() int {
	return xxx_messageInfo_PromQL_LabelsQueryResult.Size(m)
}
func (m *PromQL_LabelsQueryResult) XXX_DiscardUnknown() {
	xxx_messageInfo_PromQL_LabelsQueryResult.DiscardUnknown(m)
}

var xxx_messageInfo_PromQL_LabelsQueryResult proto.InternalMessageInfo

func (m *PromQL_LabelsQueryResult) GetLabels() []string {
	if m != nil {
		return m.Labels
	}
	return nil
}

type PromQL_LabelValuesQueryResult struct {
	Values               []string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PromQL_LabelValuesQueryResult) Reset()         { *m = PromQL_LabelValuesQueryResult{} }
func (m *PromQL_LabelValuesQueryResult) String() string { return proto.CompactTextString(m) }
func (*PromQL_LabelValuesQueryResult) ProtoMessage()    {}
func (*PromQL_LabelValuesQueryResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_0808f1dc738840d6, []int{0, 9}
}

func (m *PromQL_LabelValuesQueryResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PromQL_LabelValuesQueryResult.Unmarshal(m, b)
}
func (m *PromQL_LabelValuesQueryResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PromQL_LabelValuesQueryResult.Marshal(b, m, deterministic)
}
func (m *PromQL_LabelValuesQueryResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PromQL_LabelValuesQueryResult.Merge(m, src)
}
func (m *PromQL_LabelValuesQueryResult) XXX_Size() int {
	return xxx_messageInfo_PromQL_LabelValuesQueryResult.Size(m)
}
func (m *PromQL_LabelValuesQueryResult) XXX_DiscardUnknown() {
	xxx_messageInfo_PromQL_LabelValuesQueryResult.DiscardUnknown(m)
}

var xxx_messageInfo_PromQL_LabelValuesQueryResult proto.InternalMessageInfo

func (m *PromQL_LabelValuesQueryResult) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

type PromQL_Vector struct {
	Samples              []*PromQL_Sample `protobuf:"bytes,1,rep,name=samples,proto3" json:"samples,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *PromQL_Vector) Reset()         { *m = PromQL_Vector{} }
func (m *PromQL_Vector) String() string { return proto.CompactTextString(m) }
func (*PromQL_Vector) ProtoMessage()    {}
func (*PromQL_Vector) Descriptor() ([]byte, []int) {
	return fileDescriptor_0808f1dc738840d6, []int{0, 10}
}

func (m *PromQL_Vector) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PromQL_Vector.Unmarshal(m, b)
}
func (m *PromQL_Vector) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PromQL_Vector.Marshal(b, m, deterministic)
}
func (m *PromQL_Vector) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PromQL_Vector.Merge(m, src)
}
func (m *PromQL_Vector) XXX_Size() int {
	return xxx_messageInfo_PromQL_Vector.Size(m)
}
func (m *PromQL_Vector) XXX_DiscardUnknown() {
	xxx_messageInfo_PromQL_Vector.DiscardUnknown(m)
}

var xxx_messageInfo_PromQL_Vector proto.InternalMessageInfo

func (m *PromQL_Vector) GetSamples() []*PromQL_Sample {
	if m != nil {
		return m.Samples
	}
	return nil
}

type PromQL_Point struct {
	Time                 int64    `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	Value                float64  `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PromQL_Point) Reset()         { *m = PromQL_Point{} }
func (m *PromQL_Point) String() string { return proto.CompactTextString(m) }
func (*PromQL_Point) ProtoMessage()    {}
func (*PromQL_Point) Descriptor() ([]byte, []int) {
	return fileDescriptor_0808f1dc738840d6, []int{0, 11}
}

func (m *PromQL_Point) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PromQL_Point.Unmarshal(m, b)
}
func (m *PromQL_Point) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PromQL_Point.Marshal(b, m, deterministic)
}
func (m *PromQL_Point) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PromQL_Point.Merge(m, src)
}
func (m *PromQL_Point) XXX_Size() int {
	return xxx_messageInfo_PromQL_Point.Size(m)
}
func (m *PromQL_Point) XXX_DiscardUnknown() {
	xxx_messageInfo_PromQL_Point.DiscardUnknown(m)
}

var xxx_messageInfo_PromQL_Point proto.InternalMessageInfo

func (m *PromQL_Point) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *PromQL_Point) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type PromQL_Sample struct {
	Metric               map[string]string `protobuf:"bytes,1,rep,name=metric,proto3" json:"metric,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Point                *PromQL_Point     `protobuf:"bytes,2,opt,name=point,proto3" json:"point,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PromQL_Sample) Reset()         { *m = PromQL_Sample{} }
func (m *PromQL_Sample) String() string { return proto.CompactTextString(m) }
func (*PromQL_Sample) ProtoMessage()    {}
func (*PromQL_Sample) Descriptor() ([]byte, []int) {
	return fileDescriptor_0808f1dc738840d6, []int{0, 12}
}

func (m *PromQL_Sample) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PromQL_Sample.Unmarshal(m, b)
}
func (m *PromQL_Sample) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PromQL_Sample.Marshal(b, m, deterministic)
}
func (m *PromQL_Sample) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PromQL_Sample.Merge(m, src)
}
func (m *PromQL_Sample) XXX_Size() int {
	return xxx_messageInfo_PromQL_Sample.Size(m)
}
func (m *PromQL_Sample) XXX_DiscardUnknown() {
	xxx_messageInfo_PromQL_Sample.DiscardUnknown(m)
}

var xxx_messageInfo_PromQL_Sample proto.InternalMessageInfo

func (m *PromQL_Sample) GetMetric() map[string]string {
	if m != nil {
		return m.Metric
	}
	return nil
}

func (m *PromQL_Sample) GetPoint() *PromQL_Point {
	if m != nil {
		return m.Point
	}
	return nil
}

type PromQL_Matrix struct {
	Series               []*PromQL_Series `protobuf:"bytes,1,rep,name=series,proto3" json:"series,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *PromQL_Matrix) Reset()         { *m = PromQL_Matrix{} }
func (m *PromQL_Matrix) String() string { return proto.CompactTextString(m) }
func (*PromQL_Matrix) ProtoMessage()    {}
func (*PromQL_Matrix) Descriptor() ([]byte, []int) {
	return fileDescriptor_0808f1dc738840d6, []int{0, 13}
}

func (m *PromQL_Matrix) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PromQL_Matrix.Unmarshal(m, b)
}
func (m *PromQL_Matrix) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PromQL_Matrix.Marshal(b, m, deterministic)
}
func (m *PromQL_Matrix) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PromQL_Matrix.Merge(m, src)
}
func (m *PromQL_Matrix) XXX_Size() int {
	return xxx_messageInfo_PromQL_Matrix.Size(m)
}
func (m *PromQL_Matrix) XXX_DiscardUnknown() {
	xxx_messageInfo_PromQL_Matrix.DiscardUnknown(m)
}

var xxx_messageInfo_PromQL_Matrix proto.InternalMessageInfo

func (m *PromQL_Matrix) GetSeries() []*PromQL_Series {
	if m != nil {
		return m.Series
	}
	return nil
}

type PromQL_Series struct {
	Metric               map[string]string `protobuf:"bytes,1,rep,name=metric,proto3" json:"metric,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Points               []*PromQL_Point   `protobuf:"bytes,2,rep,name=points,proto3" json:"points,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PromQL_Series) Reset()         { *m = PromQL_Series{} }
func (m *PromQL_Series) String() string { return proto.CompactTextString(m) }
func (*PromQL_Series) ProtoMessage()    {}
func (*PromQL_Series) Descriptor() ([]byte, []int) {
	return fileDescriptor_0808f1dc738840d6, []int{0, 14}
}

func (m *PromQL_Series) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PromQL_Series.Unmarshal(m, b)
}
func (m *PromQL_Series) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PromQL_Series.Marshal(b, m, deterministic)
}
func (m *PromQL_Series) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PromQL_Series.Merge(m, src)
}
func (m *PromQL_Series) XXX_Size() int {
	return xxx_messageInfo_PromQL_Series.Size(m)
}
func (m *PromQL_Series) XXX_DiscardUnknown() {
	xxx_messageInfo_PromQL_Series.DiscardUnknown(m)
}

var xxx_messageInfo_PromQL_Series proto.InternalMessageInfo

func (m *PromQL_Series) GetMetric() map[string]string {
	if m != nil {
		return m.Metric
	}
	return nil
}

func (m *PromQL_Series) GetPoints() []*PromQL_Point {
	if m != nil {
		return m.Points
	}
	return nil
}

type PromQL_SeriesInfo struct {
	Info                 map[string]string `protobuf:"bytes,1,rep,name=info,proto3" json:"info,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PromQL_SeriesInfo) Reset()         { *m = PromQL_SeriesInfo{} }
func (m *PromQL_SeriesInfo) String() string { return proto.CompactTextString(m) }
func (*PromQL_SeriesInfo) ProtoMessage()    {}
func (*PromQL_SeriesInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_0808f1dc738840d6, []int{0, 15}
}

func (m *PromQL_SeriesInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PromQL_SeriesInfo.Unmarshal(m, b)
}
func (m *PromQL_SeriesInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PromQL_SeriesInfo.Marshal(b, m, deterministic)
}
func (m *PromQL_SeriesInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PromQL_SeriesInfo.Merge(m, src)
}
func (m *PromQL_SeriesInfo) XXX_Size() int {
	return xxx_messageInfo_PromQL_SeriesInfo.Size(m)
}
func (m *PromQL_SeriesInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PromQL_SeriesInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PromQL_SeriesInfo proto.InternalMessageInfo

func (m *PromQL_SeriesInfo) GetInfo() map[string]string {
	if m != nil {
		return m.Info
	}
	return nil
}

func init() {
	proto.RegisterType((*PromQL)(nil), "metricstore.v1.PromQL")
	proto.RegisterType((*PromQL_InstantQueryRequest)(nil), "metricstore.v1.PromQL.InstantQueryRequest")
	proto.RegisterType((*PromQL_RangeQueryRequest)(nil), "metricstore.v1.PromQL.RangeQueryRequest")
	proto.RegisterType((*PromQL_SeriesQueryRequest)(nil), "metricstore.v1.PromQL.SeriesQueryRequest")
	proto.RegisterType((*PromQL_LabelsQueryRequest)(nil), "metricstore.v1.PromQL.LabelsQueryRequest")
	proto.RegisterType((*PromQL_LabelValuesQueryRequest)(nil), "metricstore.v1.PromQL.LabelValuesQueryRequest")
	proto.RegisterType((*PromQL_InstantQueryResult)(nil), "metricstore.v1.PromQL.InstantQueryResult")
	proto.RegisterType((*PromQL_RangeQueryResult)(nil), "metricstore.v1.PromQL.RangeQueryResult")
	proto.RegisterType((*PromQL_SeriesQueryResult)(nil), "metricstore.v1.PromQL.SeriesQueryResult")
	proto.RegisterType((*PromQL_LabelsQueryResult)(nil), "metricstore.v1.PromQL.LabelsQueryResult")
	proto.RegisterType((*PromQL_LabelValuesQueryResult)(nil), "metricstore.v1.PromQL.LabelValuesQueryResult")
	proto.RegisterType((*PromQL_Vector)(nil), "metricstore.v1.PromQL.Vector")
	proto.RegisterType((*PromQL_Point)(nil), "metricstore.v1.PromQL.Point")
	proto.RegisterType((*PromQL_Sample)(nil), "metricstore.v1.PromQL.Sample")
	proto.RegisterMapType((map[string]string)(nil), "metricstore.v1.PromQL.Sample.MetricEntry")
	proto.RegisterType((*PromQL_Matrix)(nil), "metricstore.v1.PromQL.Matrix")
	proto.RegisterType((*PromQL_Series)(nil), "metricstore.v1.PromQL.Series")
	proto.RegisterMapType((map[string]string)(nil), "metricstore.v1.PromQL.Series.MetricEntry")
	proto.RegisterType((*PromQL_SeriesInfo)(nil), "metricstore.v1.PromQL.SeriesInfo")
	proto.RegisterMapType((map[string]string)(nil), "metricstore.v1.PromQL.SeriesInfo.InfoEntry")
}

func init() { proto.RegisterFile("promql.proto", fileDescriptor_0808f1dc738840d6) }

var fileDescriptor_0808f1dc738840d6 = []byte{
	// 787 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0x5f, 0x4f, 0x13, 0x4b,
	0x14, 0xbf, 0xdb, 0x3f, 0x0b, 0x3d, 0xe5, 0x72, 0xcb, 0x00, 0xbd, 0xcd, 0x5c, 0xb8, 0x41, 0x1e,
	0xb4, 0x40, 0xdc, 0x4a, 0x51, 0x11, 0x13, 0x43, 0x30, 0x31, 0x91, 0x04, 0x14, 0x16, 0xe5, 0xc5,
	0x18, 0x32, 0xd4, 0x01, 0x37, 0xee, 0xee, 0x94, 0xdd, 0x69, 0x23, 0x8a, 0x2f, 0x3e, 0xf8, 0x05,
	0x4c, 0x4c, 0x8c, 0xdf, 0xc4, 0xf8, 0x01, 0x7c, 0xf7, 0x2b, 0xf8, 0x41, 0xcc, 0x9c, 0xd9, 0x96,
	0x6e, 0xcb, 0xd6, 0x55, 0x5f, 0xc8, 0xcc, 0xf0, 0x3b, 0xbf, 0xdf, 0xef, 0xec, 0x39, 0x73, 0xa6,
	0x30, 0xd6, 0x0c, 0x84, 0x77, 0xe2, 0x5a, 0xcd, 0x40, 0x48, 0x41, 0xc6, 0x3d, 0x2e, 0x03, 0xa7,
	0x11, 0x4a, 0x11, 0x70, 0xab, 0xbd, 0x4c, 0x67, 0x8e, 0x85, 0x38, 0x76, 0x79, 0x8d, 0x35, 0x9d,
	0x1a, 0xf3, 0x7d, 0x21, 0x99, 0x74, 0x84, 0x1f, 0x6a, 0xf4, 0xfc, 0x87, 0x31, 0x30, 0x77, 0x02,
	0xe1, 0xed, 0x6e, 0xd1, 0x75, 0x98, 0xdc, 0xf4, 0x43, 0xc9, 0x7c, 0xb9, 0xdb, 0xe2, 0xc1, 0xa9,
	0xcd, 0x4f, 0x5a, 0x3c, 0x94, 0x64, 0x0a, 0xf2, 0x27, 0x6a, 0x5f, 0x31, 0xe6, 0x8c, 0x6a, 0xc1,
	0xd6, 0x1b, 0x42, 0x20, 0x27, 0x1d, 0x8f, 0x57, 0x32, 0x78, 0x88, 0x6b, 0xca, 0x61, 0xc2, 0x66,
	0xfe, 0x31, 0x4f, 0x11, 0x3e, 0x05, 0xf9, 0x50, 0xb2, 0x40, 0x46, 0xf1, 0x7a, 0x43, 0x4a, 0x90,
	0xe5, 0xfe, 0xb3, 0x4a, 0x16, 0xcf, 0xd4, 0x52, 0xc9, 0x84, 0x92, 0x37, 0x2b, 0x39, 0x2d, 0xa3,
	0xd6, 0xf4, 0x11, 0x90, 0x3d, 0x1e, 0x38, 0x3c, 0x8c, 0xe9, 0x94, 0x21, 0xef, 0x31, 0xd9, 0x78,
	0x5e, 0x31, 0xe6, 0xb2, 0xd5, 0x82, 0x3d, 0x82, 0x9b, 0x27, 0x4f, 0xd3, 0x2a, 0xd1, 0x15, 0x20,
	0x5b, 0xec, 0x90, 0xbb, 0x71, 0xd6, 0x59, 0x00, 0x57, 0x34, 0x98, 0x7b, 0x20, 0x7c, 0x57, 0xa7,
	0x30, 0x6a, 0x17, 0xf0, 0xe4, 0xa1, 0xef, 0x9e, 0xd2, 0x2d, 0xf8, 0x17, 0x83, 0xf6, 0x99, 0xdb,
	0xea, 0xf3, 0x43, 0x20, 0xe7, 0x33, 0x8f, 0x47, 0x69, 0xe3, 0xba, 0x8f, 0x2d, 0xd3, 0xcf, 0xf6,
	0xd5, 0x00, 0x12, 0xaf, 0x40, 0xd8, 0x72, 0x25, 0xb9, 0x09, 0x66, 0xd8, 0x60, 0x2e, 0x0b, 0x90,
	0xab, 0x58, 0x9f, 0xb1, 0xe2, 0x15, 0xb6, 0x74, 0xfd, 0xac, 0x1d, 0xe1, 0xf8, 0xf2, 0xfe, 0x5f,
	0x76, 0x84, 0x26, 0xab, 0x60, 0xb6, 0x79, 0x43, 0x8a, 0x00, 0x95, 0x8a, 0xf5, 0xd9, 0x84, 0xb8,
	0x7d, 0x04, 0xa9, 0x40, 0x0d, 0x57, 0x81, 0x1e, 0x93, 0x81, 0xf3, 0x12, 0xbf, 0x4f, 0x72, 0xe0,
	0x36, 0x82, 0x54, 0xa0, 0x86, 0xdf, 0x1d, 0x05, 0x53, 0x7b, 0xa6, 0x8f, 0xa1, 0xd4, 0xdb, 0x0a,
	0x98, 0xc7, 0x39, 0xad, 0xf1, 0xbb, 0xb4, 0x0f, 0x60, 0x22, 0x56, 0x7a, 0xe4, 0x5d, 0x03, 0x33,
	0xc4, 0x43, 0x2c, 0x7d, 0xb1, 0x7e, 0x29, 0x81, 0x57, 0x47, 0x6e, 0xfa, 0x47, 0xc2, 0x8e, 0x02,
	0xe8, 0x12, 0x4c, 0xc4, 0x8a, 0x8e, 0x7c, 0x65, 0x30, 0x5d, 0x3c, 0x8c, 0x5a, 0x29, 0xda, 0xd1,
	0x6b, 0x50, 0x1e, 0x2c, 0x76, 0x27, 0xa2, 0x8d, 0x87, 0x9d, 0x08, 0xbd, 0xa3, 0x1b, 0x60, 0xee,
	0x77, 0x3e, 0xe9, 0x48, 0xc8, 0xbc, 0xa6, 0xdb, 0x35, 0x99, 0x94, 0xfc, 0x1e, 0xa2, 0xec, 0x0e,
	0x9a, 0x2e, 0x43, 0x1e, 0xeb, 0xda, 0xbd, 0x70, 0xea, 0xdb, 0x65, 0xf5, 0x85, 0x53, 0xbd, 0x8d,
	0x4a, 0x58, 0x60, 0xc3, 0xd6, 0x1b, 0xfa, 0xd9, 0x00, 0x53, 0xd3, 0x90, 0x0d, 0x30, 0xb5, 0x4c,
	0xa4, 0xba, 0x30, 0x54, 0xd5, 0xda, 0xc6, 0x7f, 0xde, 0xf3, 0x65, 0x70, 0x6a, 0x47, 0x81, 0xa4,
	0x0e, 0xf9, 0xa6, 0x32, 0x10, 0x35, 0xd1, 0xd0, 0xe6, 0xb3, 0x35, 0x94, 0xae, 0x41, 0xb1, 0x87,
	0x4a, 0x5d, 0xb6, 0x17, 0xbc, 0x33, 0x00, 0xd4, 0x32, 0x6e, 0xbc, 0x10, 0x19, 0xbf, 0x9d, 0xb9,
	0x65, 0xd0, 0x75, 0x30, 0x75, 0xfd, 0xc9, 0x8d, 0xbe, 0xb2, 0xce, 0x0e, 0x2d, 0x6b, 0xb7, 0xa4,
	0x5f, 0x54, 0xf6, 0xb8, 0x4c, 0x9f, 0x3d, 0xc2, 0x2f, 0xcc, 0xfe, 0x3a, 0x98, 0x98, 0x52, 0x58,
	0xc9, 0x20, 0xc5, 0xf0, 0xf4, 0x23, 0xec, 0x9f, 0xe4, 0xff, 0xce, 0x00, 0x38, 0x6f, 0x54, 0xb2,
	0x0e, 0x39, 0xc7, 0x3f, 0x12, 0x51, 0x02, 0x4b, 0x3f, 0xed, 0x6c, 0x4b, 0xfd, 0xd1, 0x29, 0x60,
	0x20, 0x5d, 0x85, 0x42, 0xf7, 0xe8, 0x57, 0x8c, 0xd4, 0x3f, 0xe5, 0xa1, 0xa0, 0xe9, 0x37, 0x76,
	0x36, 0xc9, 0x19, 0x8c, 0xf5, 0x4e, 0x26, 0xb2, 0x98, 0xe0, 0xe4, 0x82, 0x07, 0x84, 0x2e, 0xa4,
	0xc2, 0xaa, 0x8b, 0x34, 0x3f, 0xfd, 0xf6, 0xdb, 0xf7, 0xf7, 0x99, 0x7f, 0xc8, 0xdf, 0xf8, 0x5a,
	0xb5, 0x97, 0x6b, 0xfa, 0xb5, 0x38, 0x03, 0x38, 0x9f, 0x26, 0xa4, 0x9a, 0xc0, 0x37, 0xf0, 0xf6,
	0xd0, 0x2b, 0x29, 0x90, 0xa8, 0xfb, 0x1f, 0xea, 0x4e, 0x93, 0xc9, 0x98, 0xee, 0x41, 0xa0, 0x70,
	0xe4, 0x15, 0x14, 0x7b, 0x86, 0x0e, 0x19, 0xde, 0x45, 0x31, 0xfd, 0x6a, 0x1a, 0x28, 0x1a, 0x28,
	0xa3, 0x81, 0x12, 0x19, 0xef, 0x18, 0xd0, 0xdd, 0xac, 0xb4, 0x7b, 0x06, 0x54, 0xa2, 0xf6, 0xe0,
	0xcb, 0x95, 0xa8, 0x3d, 0x30, 0xef, 0x06, 0xb5, 0xf5, 0xbc, 0x23, 0x1f, 0x0d, 0x28, 0xf5, 0x0f,
	0x3c, 0x62, 0x0d, 0xa3, 0x1d, 0x7c, 0x06, 0xe9, 0xd5, 0xd4, 0x78, 0xf4, 0x72, 0x19, 0xbd, 0xcc,
	0x91, 0xff, 0x63, 0x5e, 0x6a, 0xaf, 0xd5, 0xf3, 0x79, 0x67, 0x71, 0xf1, 0x4d, 0x4d, 0x4f, 0xd6,
	0x43, 0x13, 0x7f, 0xbd, 0xac, 0xfc, 0x08, 0x00, 0x00, 0xff, 0xff, 0x3b, 0xc0, 0x62, 0x1b, 0xfb,
	0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PromQLAPIClient is the client API for PromQLAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PromQLAPIClient interface {
	InstantQuery(ctx context.Context, in *PromQL_InstantQueryRequest, opts ...grpc.CallOption) (*PromQL_InstantQueryResult, error)
	RangeQuery(ctx context.Context, in *PromQL_RangeQueryRequest, opts ...grpc.CallOption) (*PromQL_RangeQueryResult, error)
	SeriesQuery(ctx context.Context, in *PromQL_SeriesQueryRequest, opts ...grpc.CallOption) (*PromQL_SeriesQueryResult, error)
	LabelsQuery(ctx context.Context, in *PromQL_LabelsQueryRequest, opts ...grpc.CallOption) (*PromQL_LabelsQueryResult, error)
	LabelValuesQuery(ctx context.Context, in *PromQL_LabelValuesQueryRequest, opts ...grpc.CallOption) (*PromQL_LabelValuesQueryResult, error)
}

type promQLAPIClient struct {
	cc *grpc.ClientConn
}

func NewPromQLAPIClient(cc *grpc.ClientConn) PromQLAPIClient {
	return &promQLAPIClient{cc}
}

func (c *promQLAPIClient) InstantQuery(ctx context.Context, in *PromQL_InstantQueryRequest, opts ...grpc.CallOption) (*PromQL_InstantQueryResult, error) {
	out := new(PromQL_InstantQueryResult)
	err := c.cc.Invoke(ctx, "/metricstore.v1.PromQLAPI/InstantQuery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promQLAPIClient) RangeQuery(ctx context.Context, in *PromQL_RangeQueryRequest, opts ...grpc.CallOption) (*PromQL_RangeQueryResult, error) {
	out := new(PromQL_RangeQueryResult)
	err := c.cc.Invoke(ctx, "/metricstore.v1.PromQLAPI/RangeQuery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promQLAPIClient) SeriesQuery(ctx context.Context, in *PromQL_SeriesQueryRequest, opts ...grpc.CallOption) (*PromQL_SeriesQueryResult, error) {
	out := new(PromQL_SeriesQueryResult)
	err := c.cc.Invoke(ctx, "/metricstore.v1.PromQLAPI/SeriesQuery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promQLAPIClient) LabelsQuery(ctx context.Context, in *PromQL_LabelsQueryRequest, opts ...grpc.CallOption) (*PromQL_LabelsQueryResult, error) {
	out := new(PromQL_LabelsQueryResult)
	err := c.cc.Invoke(ctx, "/metricstore.v1.PromQLAPI/LabelsQuery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promQLAPIClient) LabelValuesQuery(ctx context.Context, in *PromQL_LabelValuesQueryRequest, opts ...grpc.CallOption) (*PromQL_LabelValuesQueryResult, error) {
	out := new(PromQL_LabelValuesQueryResult)
	err := c.cc.Invoke(ctx, "/metricstore.v1.PromQLAPI/LabelValuesQuery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PromQLAPIServer is the server API for PromQLAPI service.
type PromQLAPIServer interface {
	InstantQuery(context.Context, *PromQL_InstantQueryRequest) (*PromQL_InstantQueryResult, error)
	RangeQuery(context.Context, *PromQL_RangeQueryRequest) (*PromQL_RangeQueryResult, error)
	SeriesQuery(context.Context, *PromQL_SeriesQueryRequest) (*PromQL_SeriesQueryResult, error)
	LabelsQuery(context.Context, *PromQL_LabelsQueryRequest) (*PromQL_LabelsQueryResult, error)
	LabelValuesQuery(context.Context, *PromQL_LabelValuesQueryRequest) (*PromQL_LabelValuesQueryResult, error)
}

func RegisterPromQLAPIServer(s *grpc.Server, srv PromQLAPIServer) {
	s.RegisterService(&_PromQLAPI_serviceDesc, srv)
}

func _PromQLAPI_InstantQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PromQL_InstantQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromQLAPIServer).InstantQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metricstore.v1.PromQLAPI/InstantQuery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromQLAPIServer).InstantQuery(ctx, req.(*PromQL_InstantQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PromQLAPI_RangeQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PromQL_RangeQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromQLAPIServer).RangeQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metricstore.v1.PromQLAPI/RangeQuery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromQLAPIServer).RangeQuery(ctx, req.(*PromQL_RangeQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PromQLAPI_SeriesQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PromQL_SeriesQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromQLAPIServer).SeriesQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metricstore.v1.PromQLAPI/SeriesQuery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromQLAPIServer).SeriesQuery(ctx, req.(*PromQL_SeriesQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PromQLAPI_LabelsQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PromQL_LabelsQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromQLAPIServer).LabelsQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metricstore.v1.PromQLAPI/LabelsQuery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromQLAPIServer).LabelsQuery(ctx, req.(*PromQL_LabelsQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PromQLAPI_LabelValuesQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PromQL_LabelValuesQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromQLAPIServer).LabelValuesQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metricstore.v1.PromQLAPI/LabelValuesQuery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromQLAPIServer).LabelValuesQuery(ctx, req.(*PromQL_LabelValuesQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PromQLAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "metricstore.v1.PromQLAPI",
	HandlerType: (*PromQLAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InstantQuery",
			Handler:    _PromQLAPI_InstantQuery_Handler,
		},
		{
			MethodName: "RangeQuery",
			Handler:    _PromQLAPI_RangeQuery_Handler,
		},
		{
			MethodName: "SeriesQuery",
			Handler:    _PromQLAPI_SeriesQuery_Handler,
		},
		{
			MethodName: "LabelsQuery",
			Handler:    _PromQLAPI_LabelsQuery_Handler,
		},
		{
			MethodName: "LabelValuesQuery",
			Handler:    _PromQLAPI_LabelValuesQuery_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "promql.proto",
}
